### ISSUE TITLE
Processor test "01-Services.js" on Part-Two has a typo

### ISSUE THREAD

**Issue by sschaefer-rms** [hyperledger/education-cryptomoji#110]
Line 254 defines the `address` as `5f4d7702` when it should be have a valid namespace prefix attached to it (`5f4d76`). Have an invalid namespace will short circuit the test since it has an invalid namespace and never gets to test for valid hex.

**Comment by therobinkim** [comment]
Thanks for nothing this issue, @sschaefer-rms! Agreed that https://github.com/hyperledger/education-cryptomoji/blob/master/code/part-two/processor/tests/01-Services.js#L256 may short circuit as per https://github.com/hyperledger/education-cryptomoji/blob/master/code/part-two/processor/services/addressing.js#L71. Let me know if you'd like to submit a fix for this issue yourself, otherwise we'll add it to our backlog!

**Comment by therobinkim** [comment]
Fixed by #113
