### ISSUE TITLE
01-Signing.js - 'sign' function is taking in Buffer, might need to add 'toString('hex')'

### ISSUE THREAD

**Issue by evalineBai** [hyperledger/education-cryptomoji#88]

**Comment by emelendez89** [comment]
https://github.com/hyperledger/education-cryptomoji/blob/dd3d2b38ec59471735b0e28bea37e707f53a32d4/code/part-one/tests/01-Signing.js#L69
Should take Buffer as it shown in [the documentation](https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md#signbuffer-message-buffer-privatekey--object-options---signature-buffer-recovery-number)

**Comment by delventhalz** [comment]
The use of `randomBytes` to create random messages for testing has caused some confusion. The simplest `sign` implementation will likely handle either strings or Buffers fine (because `createHash` handles both strings and Buffers), so I was not particularly specific about which to accept. This is clarified in a new PR:

- part one's sign method must be able to handle strings
- part two's sign method must be able to handle Buffers
